import '../../styles/report-template.css';

export interface ReportTemplateData {
  studyId: string;
  status: string;
  source: string;
  validated: boolean;
  findings: string;
  impression: string;
  createdAt: string;
  updatedAt: string;
  signedAt?: string;
  radiologistName?: string;
  radiologistDesignation?: string;
  signatureDataUrl?: string;
  patientName?: string;
  patientAge?: string;
  patientSex?: string;
  patientId?: string;
}

interface ReportTemplateProps {
  data: ReportTemplateData;
  /** ID used by html2canvas to find this element */
  id?: string;
}

const CENTRE = {
  name: 'PRISM Diagnostic Centre',
  tagline: 'AI-Powered Radiology Intelligence Platform',
  address: '4th Floor, MedTech Tower, Bengaluru — 560001, Karnataka, India',
  phone: '+91 80 4567 8900',
  email: 'reports@prism-diagnostic.in',
  website: 'www.prism-diagnostic.in',
  regNo: 'KAR/DIA/2024/0042',
};

function formatDate(iso: string) {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleString('en-IN', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: true,
      timeZone: 'Asia/Kolkata',
    });
  } catch { return iso.slice(0, 16); }
}

function todayIST() {
  return new Date().toLocaleString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
    timeZone: 'Asia/Kolkata',
  });
}

export function ReportTemplate({ data, id = 'prism-report-template' }: ReportTemplateProps) {
  const reportDate = todayIST();

  return (
    <div id={id} className="report-a4">
      <div className="report-a4-inner" style={{ paddingBottom: 100 }}>

        {/* ── HEADER ── */}
        <div className="report-header-bar">
          <div className="report-centre-info">
            {/* Logo mark */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
              <div style={{
                width: 38, height: 38, borderRadius: 9,
                background: 'linear-gradient(135deg, #0ea5e9, #6366f1)',
                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
              }}>
                <svg style={{ width: 20, height: 20, color: '#fff' }} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                    d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082" />
                </svg>
              </div>
              <div>
                <h1>{CENTRE.name}</h1>
                <p style={{ fontSize: 10, color: '#6366f1', fontWeight: 600 }}>{CENTRE.tagline}</p>
              </div>
            </div>
            <p>{CENTRE.address}</p>
            <p>Ph: {CENTRE.phone} &nbsp;|&nbsp; {CENTRE.email}</p>
            <p>Reg. No: {CENTRE.regNo}</p>
          </div>

          <div className="report-meta-box">
            <div className="report-id">RPT-{data.studyId}</div>
            <p><strong>Report Date:</strong> {reportDate}</p>
            <p><strong>Status:</strong>&nbsp;
              <span style={{ color: data.status === 'signed' ? '#16a34a' : '#d97706', fontWeight: 700, textTransform: 'uppercase' }}>
                {data.status}
              </span>
            </p>
            <p><strong>Source:</strong> {data.source?.toUpperCase() || 'TEMPLATE'}</p>
            <p style={{ marginTop: 6, fontSize: 10, color: '#94a3b8' }}>Generated by PRISM Phase 3 AI</p>
          </div>
        </div>

        {/* Validated stamp */}
        {data.validated && (
          <div className="validated-stamp">
            <span>AI<br />VALID<br />ATED</span>
          </div>
        )}

        {/* ── STUDY INFO STRIP ── */}
        <div className="study-info-strip">
          <div className="study-info-cell">
            <label>Patient Name</label>
            <span style={{ fontFamily: 'inherit', letterSpacing: 0 }}>{data.patientName || '—'}</span>
          </div>
          <div className="study-info-cell">
            <label>Patient ID</label>
            <span>{data.patientId || '—'}</span>
          </div>
          <div className="study-info-cell">
            <label>Age / Sex</label>
            <span style={{ fontFamily: 'inherit' }}>
              {[data.patientAge, data.patientSex].filter(Boolean).join(' / ') || '—'}
            </span>
          </div>
          <div className="study-info-cell">
            <label>Modality</label>
            <span>CT Scan</span>
          </div>
          <div className="study-info-cell">
            <label>Report Generated</label>
            <span style={{ fontSize: 11 }}>{formatDate(data.createdAt)}</span>
          </div>
        </div>

        {/* ── CLINICAL DISCLAIMER ── */}
        <div style={{
          background: '#fff7ed', border: '1px solid #fed7aa', borderRadius: 6,
          padding: '8px 14px', marginBottom: 20, fontSize: 10, color: '#92400e',
          display: 'flex', alignItems: 'flex-start', gap: 8,
        }}>
          <span style={{ fontWeight: 700, flexShrink: 0 }}>⚠ DRAFT REPORT —</span>
          <span>
            This AI-generated report is intended for use by a licensed radiologist only.
            It must be reviewed and signed before clinical use. Not valid without radiologist's digital signature.
          </span>
        </div>

        {/* ── FINDINGS ── */}
        <div className="report-section">
          <div className="report-section-title">Clinical Findings</div>
          <div className="report-section-body">
            {data.findings || 'No findings recorded.'}
          </div>
        </div>

        {/* ── IMPRESSION ── */}
        <div className="report-section report-impression">
          <div className="report-section-title">Radiologist Impression</div>
          <div className="report-section-body">
            {data.impression || 'No impression recorded.'}
          </div>
        </div>

        {/* Validation note */}
        {data.validated !== undefined && (
          <div style={{
            padding: '8px 14px', borderRadius: 6, marginBottom: 20,
            background: data.validated ? '#f0fdf4' : '#fef2f2',
            border: `1px solid ${data.validated ? '#bbf7d0' : '#fecaca'}`,
            fontSize: 11,
            color: data.validated ? '#166534' : '#991b1b',
          }}>
            <strong>AI Validation:</strong>&nbsp;
            {data.validated
              ? '✓ Report passed anti-hallucination validation gate. All findings are grounded in structured input data.'
              : '✗ Validation flag raised. Please verify findings against raw study data before signing.'}
          </div>
        )}

        {/* ── SIGNATURE BLOCK ── */}
        <div className="signature-block">
          <div className="signature-left">
            <p style={{ fontSize: 10, color: '#94a3b8', marginBottom: 8 }}>
              {data.status === 'signed'
                ? `Digitally signed on ${data.signedAt ? formatDate(data.signedAt) : reportDate}`
                : 'Awaiting radiologist signature'}
            </p>
            <p className="signature-name">{data.radiologistName || 'Dr. [Radiologist Name]'}</p>
            <p className="signature-designation">{data.radiologistDesignation || 'MD Radiology | FRCR'}</p>
            <p style={{ fontSize: 10, color: '#94a3b8', marginTop: 4 }}>{CENTRE.name}</p>
          </div>

          <div style={{ textAlign: 'center' }}>
            <p style={{ fontSize: 9, color: '#94a3b8', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.08em' }}>
              Digital Signature
            </p>
            <div className="signature-image-box">
              {data.signatureDataUrl ? (
                <img src={data.signatureDataUrl} alt="Digital Signature" />
              ) : (
                <span style={{ fontSize: 11, color: '#cbd5e1', fontStyle: 'italic' }}>
                  {data.status === 'signed' ? 'Signature on file' : 'Not yet signed'}
                </span>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* ── REPORT FOOTER ── */}
      <div className="report-footer">
        <p>{CENTRE.name} · {CENTRE.address}</p>
        <span className="report-ai-badge">PRISM AI · Phase 3</span>
        <p>Page 1 of 1 · {CENTRE.website}</p>
      </div>
    </div>
  );
}
