import json
import logging
import time
from .hu_reference_table import HU_REFERENCE_TABLE, HU_REFERENCE_TABLE_CECT, detect_region
from .classifier import classify_structure
from .contrast_detection import detect_contrast_from_voxels

logger = logging.getLogger(__name__)

class Phase2Orchestrator:
    """
    Phase 2 Orchestrator.
    Currently mocks TotalSegmentator execution and generates preliminary findings JSON.
    """
    def __init__(self):
        pass

    def mock_totalsegmentator_statistics(self) -> dict:
        """
        Mocks the `--statistics` JSON output from TotalSegmentator.
        In a real scenario, this is read from `statistics.json` generated by TotalSegmentator.
        """
        return {
            "aorta": {"mean": 210.5, "volume": 150.2},
            "liver": {"mean": 115.3, "volume": 1500.5},
            "spleen": {"mean": 125.0, "volume": 200.1},
            "kidney_cortex": {"mean": 140.2, "volume": 180.5},
            "pancreas": {"mean": 45.0, "volume": 80.0}, # Mocking an anomaly (hypo-enhancing)
            "lung_parenchyma": {"mean": -850.0, "volume": 4000.0}
        }

    def run_pipeline(self) -> dict:
        t_start = time.perf_counter()
        
        # 1. Mock TotalSegmentator execution
        logger.info("Mocking TotalSegmentator execution...")
        stats = self.mock_totalsegmentator_statistics()
        present_labels = list(stats.keys())

        # 2. Identify Body Part Region
        region = detect_region(present_labels)
        logger.info(f"Detected Region: {region}")

        # 3. Detect Contrast Phase
        aorta_mean = stats.get("aorta", {}).get("mean")
        liver_mean = stats.get("liver", {}).get("mean")
        
        contrast_phase = detect_contrast_from_voxels(
            aorta_mean_hu=aorta_mean, 
            liver_mean_hu=liver_mean
        )
        logger.info(f"Detected Contrast Phase: {contrast_phase}")

        # 4. Select appropriate HU Reference Table
        if contrast_phase in ["CONTRAST_PORTAL_VENOUS", "CONTRAST_ARTERIAL"]:
            active_table = HU_REFERENCE_TABLE_CECT
            logger.info("Loaded CECT Reference Table.")
        else:
            active_table = HU_REFERENCE_TABLE
            logger.info("Loaded Non-Contrast Reference Table.")

        # 5. Classify Structures and generate findings
        findings = []
        for organ, data in stats.items():
            mean_hu = data.get("mean")
            result = classify_structure(organ, mean_hu=mean_hu, table=active_table)
            
            # Add volume and calculate subtractive anomaly localization mockup
            result["volume_cc"] = data.get("volume")
            
            # Calculate Ratio vs Aorta if CECT
            if contrast_phase != "NON_CONTRAST" and aorta_mean and organ != "aorta":
                result["aorta_ratio"] = round(mean_hu / aorta_mean, 2)
                
            findings.append(result)

        # 6. Package Output
        payload = {
            "metadata": {
                "detected_region": region,
                "contrast_phase": contrast_phase,
                "processing_time_ms": round((time.perf_counter() - t_start) * 1000, 2),
                "mocked_segmentation": True
            },
            "findings": findings
        }

        return payload

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    orchestrator = Phase2Orchestrator()
    results = orchestrator.run_pipeline()
    print(json.dumps(results, indent=2))
